apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: security-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: security-exporter
  namespaceSelector:
    matchNames:
      - security
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
