apiVersion: v1
kind: Service
metadata:
  name: {{ include "security-exporter.fullname" . }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.port }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: security-exporter
