apiVersion: v1
kind: Service
metadata:
  name: security-exporter
  namespace: security
  labels:
    app: security-exporter
spec:
  selector:
    app: security-exporter
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
